# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
  strut.presentation_repository:
          class: Strut\StrutBundle\Repository\PresentationRepository
          factory: [ "@doctrine.orm.default_entity_manager", getRepository ]
          arguments:
              - Strut:Presentation
              - StrutUserBundle:User

  strut.users_repository:
          class: Strut\UserBundle\Repository\UsersRepository
          factory: [ "@doctrine.orm.default_entity_manager", getRepository ]
          arguments:
              - StrutUserBundle:User

  strut.user_group_repository:
          class: Strut\GroupBundle\Repository\UserGroupRepository
          factory: [ "@doctrine.orm.default_entity_manager", getRepository ]
          arguments:
              - StrutGroupBundle:UserGroup

  strut.version_repository:
            class: Strut\StrutBundle\Repository\VersionRepository
            factory: [ "@doctrine.orm.default_entity_manager", getRepository ]
            arguments:
                - Strut:Version

  strut.picture_repository:
            class: Strut\StrutBundle\Repository\PictureRepository
            factory: [ "@doctrine.orm.default_entity_manager", getRepository ]
            arguments:
                - Strut:Picture

  twig.extension.date:
          class: Twig_Extensions_Extension_Date
          arguments:
              - "@translator.default"
          tags:
              - { name: twig.extension }

  strut.locale_listener:
      class: Strut\StrutBundle\Event\Listener\LocaleListener
      arguments: ["%kernel.default_locale%"]
      tags:
          - { name: kernel.event_subscriber }

  strut.user_locale_listener:
      class: Strut\StrutBundle\Event\Listener\UserLocaleListener
      arguments: ["@session"]
      tags:
          - { name: kernel.event_listener, event: security.interactive_login, method: onInteractiveLogin }

  strut.listener.create_config:
      class: Strut\StrutBundle\Event\Listener\CreateConfigListener
      arguments:
          - "@doctrine.orm.entity_manager"
          - "%strut.language%"
      tags:
          - { name: kernel.event_subscriber }
