services:
  strut.presentation_repository:
          class: Strut\StrutBundle\Repository\PresentationRepository
          factory: [ "@doctrine.orm.default_entity_manager", getRepository ]
          arguments:
              - Strut:Presentation
              - StrutUserBundle:User

  strut.users_repository:
          class: Strut\UserBundle\Repository\UsersRepository
          factory: [ "@doctrine.orm.default_entity_manager", getRepository ]
          arguments:
              - StrutUserBundle:User

  strut.user_group_repository:
          class: Strut\GroupBundle\Repository\UserGroupRepository
          factory: [ "@doctrine.orm.default_entity_manager", getRepository ]
          arguments:
              - StrutGroupBundle:UserGroup

  strut.version_repository:
            class: Strut\StrutBundle\Repository\VersionRepository
            factory: [ "@doctrine.orm.default_entity_manager", getRepository ]
            arguments:
                - Strut:Version

  strut.picture_repository:
            class: Strut\StrutBundle\Repository\PictureRepository
            factory: [ "@doctrine.orm.default_entity_manager", getRepository ]
            arguments:
                - Strut:Picture

  twig.extension.date:
          class: Twig_Extensions_Extension_Date
          arguments:
              - "@translator.default"
          tags:
              - { name: twig.extension }

  strut.locale_listener:
      class: Strut\StrutBundle\Event\Listener\LocaleListener
      arguments: ["%kernel.default_locale%"]
      tags:
          - { name: kernel.event_subscriber }

  strut.user_locale_listener:
      class: Strut\StrutBundle\Event\Listener\UserLocaleListener
      arguments: ["@session"]
      tags:
          - { name: kernel.event_listener, event: security.interactive_login, method: onInteractiveLogin }

  strut.listener.create_config:
      class: Strut\StrutBundle\Event\Listener\CreateConfigListener
      arguments:
          - "@doctrine.orm.entity_manager"
          - "%strut.language%"
      tags:
          - { name: kernel.event_subscriber }

  sha256salted_encoder:
      class: Strut\GroupBundle\Service\Sha256Salted

  strut.slides.stats:
      class: Strut\SlideBundle\Helper\ProvideStats
      arguments:
          - "@strut.slides.mapper"

  strut.slides.first_picture:
        class: Strut\SlideBundle\Helper\FirstPicture
        arguments:
            - "@strut.slides.mapper"

  strut.slides.mapper:
        class: Strut\SlideBundle\Helper\PresentationMapper
        arguments:
            - "@logger"

  strut.twig_extension:
          class: Strut\SlideBundle\Twig\StrutExtension
          public: false
          tags:
              - { name: twig.extension }
  strut.check_rights:
      class: Strut\StrutBundle\Helper\CheckRights
      arguments:
          - "@logger"

  strut.remove_picture:
      class: Strut\StrutBundle\Event\Listener\RemovePictureListener
      arguments:
          - "%pictures_directory%"
          - "@logger"
      tags:
          - { name: doctrine.event_listener, event: postRemove }

  filesystem_cache:
      class: Doctrine\Common\Cache\FilesystemCache
      arguments:
          - "%kernel.cache_dir%/doctrine/metadata"