services:

    strut.form.type.config:
          class: Strut\StrutBundle\Form\Type\ConfigType
          arguments:
              - "%strut.languages%"
          tags:
              - { name: form.type }

    sha256salted_encoder:
          class: Strut\StrutBundle\Service\Sha256Salted